env:
  global:
    - TERM=dumb
    - secure: hEB/oRcqBtM9XAtI3X77TzA+h0h6/W6bG2b4Zb1ypwukAnKZg6ziuKKFHU06uM3r710GY8kNSP/xMq4hoaQjQstml2RUDudH3Bo6n33BbOcotQr/YnTYBQPyvJpE7aVyEpDDnmaygJfw667HSgr9tfcmLwkgOH8aeYF4MUhuL77xJJm683/K3IO8KRfDRxlFMFuYwI4f7yoVZxxDFYDcUA6aqDzZCYCwVSQ+71GtVTtoe+g+asHUM+GgoNq8rlpw55Wqzy37dxwt4eyMCSIVbzbXrs+iCbg9UTJK8qvl2ahfEC1ECj7Iuus/ff8iLw14cgmLF6Z7lSB9390+Iq1AS2bpVy4zykgZAIn+qPPZyCkqBlZZBpiVPq1QsqqTlRYonuSytJNYbSVXmdaK0DJLg0DdRzYV8nohvD/HvTErYhhjIO6vDKv8piZ2aAboRhzTVUNVFvFMoaQ5667gR9NWvpECXNgqPRVBprjqAZD7Cfljzpv4rZi+ppkE4dAEpQcURRgVOtVTi62NtL9TnqPqdxf/zmB7eDMYMwN1iEij18ZjlRp8m3xP4Dqo2EdOtKPBu+Iia6AVEARRljyxPV6WSm0DB0t3HSvL6sVUkPibYwfuCVv0CuIzw7wsqUE/8V6bcHT72uSqmVEXIOESb13eAkGrBrrDNE9HY4g7PUrXnEA=
dist: trusty
notifications:
  email: false
git:
  quiet: true
  depth: 1
language: java
jdk: openjdk8
node_js: lts/*
python: 3
service:
  - docker
  - xvfb
addons:
  apt:
    update: true
    sources:
      - google-chrome
    packages:
      - jq
      - bash
      - sudo
      - lsof
      - wget
      - curl
      - unzip
      - docker-ce
      - python3-pip
      - libappindicator1
      - fonts-liberation
      - google-chrome-stable
install: true
before_install:
  ## use instead:
  ##
  ## services:
  ##   - xvfb
  ##
  #- export CHROME_BIN=/usr/bin/google-chrome
  #- export DISPLAY=:99.0
  #- sh -e /etc/init.d/xvfb start
  ##
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user $(whoami) --upgrade pip
  - pip install --user $(whoami) --upgrade httpie
  - http --version --debug
  - docker-compose -v
  #
  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
  - stop_any 80 8001 8002 8080 5432
stages:
  - test
  - deploy
jobs:
  include:
    - stage: test
      jdk: openjdk8
      name: tests
      script: cd $TRAVIS_BUILD_DIR && ./gradlew test
    - stage: test
      jdk: openjdk11
      name: tests (openjdk11)
      script: cd $TRAVIS_BUILD_DIR && ./gradlew test
    - stage: test
      jdk: openjdk8
      name: default tasks
      script: cd $TRAVIS_BUILD_DIR && ./gradlew
    - stage: test
      jdk: openjdk11
      name: default tasks (openjdk11)
      script: cd $TRAVIS_BUILD_DIR && ./gradlew
    - stage: test
      jdk: openjdk8
      name: integration tests
      script:
        - cd $TRAVIS_BUILD_DIR && ./gradlew assemble
        - java -jar $TRAVIS_BUILD_DIR/build/libs/*.jar &
        - wait_for 8080
        - http :8080 | jq '.'
        - http :8080/tweets | jq '.'
        - http :8080/tweets body="hello mvc" | jq '.'
        - http :8080/tweets/tags | jq '.'
        - stop_any 80 8080
    - stage: test
      jdk: openjdk11
      name: integration tests (openjdk11)
      script:
        - cd $TRAVIS_BUILD_DIR && ./gradlew assemble
        - java -jar $TRAVIS_BUILD_DIR/build/libs/*.jar &
        - wait_for 8080
        - http :8080 | jq '.'
        - http :8080/tweets | jq '.'
        - http :8080/tweets body="hello mvc" | jq '.'
        - http :8080/tweets/tags | jq '.'
        - stop_any 80 8080
    - stage: test
      jdk: openjdk8
      name: integration tests with docker-compose
      script:
        - cd $TRAVIS_BUILD_DIR && ./gradlew assemble composeUp
        - wait_for 8080
        - http :8080 | jq '.'
        - http :8080/tweets | jq '.'
        - http :8080/tweets body="hello mvc" | jq '.'
        - http :8080/tweets/tags | jq '.'
        - cd $TRAVIS_BUILD_DIR && ./gradlew composeDown
        - stop_any 80 8080
    - stage: test
      jdk: openjdk11
      name: integration tests with docker-compose (openjdk11)
      script:
        - cd $TRAVIS_BUILD_DIR && ./gradlew assemble composeUp
        - wait_for 8080
        - http :8080 | jq '.'
        - http :8080/tweets | jq '.'
        - http :8080/tweets body="hello mvc" | jq '.'
        - http :8080/tweets/tags | jq '.'
        - cd $TRAVIS_BUILD_DIR && ./gradlew composeDown
        - stop_any 80 8080
    - stage: test
      jdk: openjdk8
      name: gradle dependencyUpdates
      script: cd $TRAVIS_BUILD_DIR && ./gradlew dependencyUpdates
    - stage: test
      jdk: openjdk11
      name: gradle dependencyUpdates (openjdk11)
      script: cd $TRAVIS_BUILD_DIR && ./gradlew dependencyUpdates
    - stage: deploy
      #jdk: openjdk8
      jdk: openjdk11
      name: GitHub release and GitHub pages deployment (openjdk11)
      script: skip
      if: branch = "master" AND type NOT IN (pull_request)
      before_deploy:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ] || [ ".$TRAVIS_BRANCH" != ".master" ] ; then exit 0 ; fi
        - env
        # documentation
        - cd $TRAVIS_BUILD_DIR && ./gradlew npm_run_gh-pages
      deploy: &pages
        provider: pages
        skip-cleanup: true
        github-token: "$GITHUB_TOKEN"
        keep-history: true
        local-dir: .vuepress/dist
        target_branch: gh-pages
        on:
          branch: master
          condition: "$TRAVIS_PULL_REQUEST = false"
cache:
  directories:
    - ~/.docker
    - ~/.gradle
    - ~/.embedmongo/
  packages: true
  pip: true
